# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
x=np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [6]:
x=np.arange(10,49)

4. Find the shape of previous array in question 3

In [8]:
print(x.shape)

(39,)


5. Print the type of the previous array in question 3

In [9]:
print(x.dtype)

int32


6. Print the numpy version and the configuration


In [10]:
print(np.__version__)
print(np.show_config())

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/MWAQAS/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/MWAQAS/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/MWAQAS/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\l

7. Print the dimension of the array in question 3


In [11]:
print(x.ndim)

1


8. Create a boolean array with all the True values

In [14]:
x=np.array([[True, True],
            [True, True]])

[[ True  True]
 [ True  True]]


9. Create a two dimensional array




In [16]:
x1=np.array([[1, 2],
            [3, 4]])

10. Create a three dimensional array



In [34]:
x2=np.array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],
       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])
#print(x2.ndim)

#or
x3=np.zeros((2,3,4))

# print(x3.ndim)
# print(x3)

3
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [37]:
x4=np.arange(1,15)
print("Orignal vector:",x4)
x4=x4[::-1]
print("Reverse vector:",x4)

Orignal vector: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Reverse vector: [14 13 12 11 10  9  8  7  6  5  4  3  2  1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [40]:
x5=np.zeros(10)
x5[5]=1
print(x5)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [41]:
x6=np.identity(3)
print(x6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [48]:
x7 = np.array([1, 2, 3, 4, 5])
print(x7.dtype)
x7=x7.astype(np.float32)
print(x7.dtype)

int32
float32


15. arr1 = np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [56]:
arr1 = np.array([[1., 2., 3.],
                 [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
                 [7., 2., 12.]])
arr3=np.multiply(arr2, arr1)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [59]:
arr1 = np.array([[1., 2., 3.],
                 [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],
                 [7., 2., 12.]])
arr3=np.array_equal(arr1, arr2)
print(arr3)

False


17. Extract all odd numbers from arr with values(0-9)

In [82]:
arr4=np.arange(0,10)
arr5=arr4[arr4%2==1]
print(arr5)

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [84]:
arr6 = arr5[arr5%2==1]= -1
print(arr6)

-1


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [95]:
arr7 = np.arange(10)
arr8=arr7[5:9]= 12
print(arr7)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [103]:
x8 = np.zeros((3,3))
print("Original array:")
print(x8)
print("array with border 1 and zero inside")
x = np.pad(x8, pad_width=1, mode='constant', constant_values=1)
print(x)

Original array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
array with border 1 and zero inside
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [116]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])
print(np.where(arr2d==5,12,arr2d))


[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [118]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(np.where(arr3d<4,64,arr3d))

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [123]:
array1 = np.array([[0, 1],
                [2, 3],
                [4, 5],
                [6, 7],
                [8, 9]])
slice=array1[:1,:2]
print(slice)

[[0 1]]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [131]:
array1 = np.array([[0, 1],
                [2, 3],
                [4, 5],
                [6, 7],
                [8, 9]])
slice2=array1[1:2, 1]
print(slice2)

[3]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [133]:
array1 = np.array([[0, 1],
                [2, 3],
                [4, 5],
                [6, 7],
                [8, 9]])
slice3=array1[2:3, :2]
print(slice3)

[[4 5]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [137]:
X = np.random.random((10,10))
print("Original Array:")
print(X) 
xmin, xmax = X.min(), X.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.19031819 0.5546566  0.61582667 0.80587212 0.15273602 0.83005206
  0.06928739 0.39087319 0.89841196 0.186443  ]
 [0.87643748 0.3952413  0.51213069 0.25267678 0.61854962 0.35229381
  0.84048222 0.71225098 0.79530917 0.93526598]
 [0.92817497 0.02105157 0.50491061 0.63875775 0.49173032 0.02158417
  0.42546111 0.29042077 0.49652479 0.97608001]
 [0.2799285  0.35255808 0.64297774 0.64507418 0.29480809 0.08566505
  0.004164   0.8386548  0.94876123 0.85769557]
 [0.95060138 0.79218974 0.92974204 0.97169203 0.73364245 0.14323869
  0.51914057 0.98226194 0.89015714 0.78044058]
 [0.25087852 0.44088033 0.74116689 0.35133588 0.90821601 0.94099232
  0.39368764 0.25372756 0.00960172 0.70486421]
 [0.08387545 0.96877967 0.65766413 0.90369753 0.25673892 0.29638571
  0.63554086 0.49089858 0.14394583 0.31308731]
 [0.81906402 0.20974763 0.3606962  0.7712671  0.84892728 0.19537777
  0.42057339 0.18616368 0.05648483 0.09213821]
 [0.64288697 0.53470593 0.30864165 0.40758565 0.31729778 0.91164

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [18]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [145]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
ab, a_ind, b_ind=np.intersect1d(a, b, return_indices=True)
print(a_ind)
print(b_ind)
print(ab)

[1 5]
[1 5]
[2 4]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [8]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
res = data[names != 'Will']
print(res)

[[ 0.17268794  0.82007511 -1.23919306  0.7839802 ]
 [ 2.57879489  0.92526884  1.55303369 -0.62627541]
 [ 0.67362153 -1.08431519 -2.05555466 -0.22339212]
 [ 0.43684443 -1.2033156   0.63855659  0.55071161]
 [-0.70872105 -1.09573012  1.41041293 -0.84962444]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [10]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
nam = (names != 'Will') & (names != 'Joe')
res2 = data[nam]
print(res2)

[[-2.55002595  0.51142918 -1.3355147  -0.42981955]
 [ 1.39725185  0.46750126 -0.05062167  0.97766302]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [12]:
rand_arr = np.random.uniform(1,15, size=(5,3))
print(rand_arr)

[[ 7.32469598  1.47771407  2.85003553]
 [ 7.59904773 10.19603908  7.47107425]
 [ 9.0360369  12.08800499  7.46093794]
 [ 4.43448652 11.04198702  8.56351297]
 [ 6.94437921  9.18459039  5.62771748]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [13]:
rand_arr1 = np.random.uniform(1,16, size=(2,2,4))
print(rand_arr1)

[[[14.62951368  8.63195438 10.18688898  4.00419377]
  [14.2312554   2.17749268 12.93691621 13.29726867]]

 [[14.3082953   4.96787257  3.49129191 12.66089232]
  [ 5.28173388  1.39924567 15.591163   14.91612123]]]


33. Swap axes of the array you created in Question 32

In [17]:
np.swapaxes(rand_arr1,0,2)

array([[[14.62951368, 14.3082953 ],
        [14.2312554 ,  5.28173388]],

       [[ 8.63195438,  4.96787257],
        [ 2.17749268,  1.39924567]],

       [[10.18688898,  3.49129191],
        [12.93691621, 15.591163  ]],

       [[ 4.00419377, 12.66089232],
        [13.29726867, 14.91612123]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [29]:
Z = np.random.random((10))
sqtz=np.sqrt(Z)
sqtz[sqtz<0.5]=0
sqtz

array([0.61591606, 0.        , 0.78832072, 0.78093563, 0.        ,
       0.6733114 , 0.81405127, 0.73821938, 0.66897194, 0.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [33]:
array1 = np.random.random(12)
array2 = np.random.random(12)
print("array one:")
print(array1)
print("array two:")
print(array2)
print("array three maximum:")
array3 = np.max(array1), np.max(array2)  
array3

array one:
[0.37554911 0.38672534 0.49691766 0.18295417 0.87409008 0.64137116
 0.75542867 0.45864117 0.62249531 0.08240682 0.52935637 0.94297748]
array two:
[0.68327925 0.59274549 0.96552279 0.04517573 0.98296941 0.9208245
 0.00234394 0.28238712 0.11607695 0.77201773 0.31792778 0.63663404]
array three maximum:


(0.942977480574871, 0.9829694132076576)

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [35]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
resnames=np.unique(names)
sortnames=np.sort(resnames)
print(sortnames)

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [39]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c=np.setdiff1d(a,b)
c

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [47]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]]).reshape(3,1)
res1=np.delete(sampleArray, 1, 1)
res = np.insert(res1, [1], newColumn, axis=1)
print(res)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [48]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z = np.dot(x,y)
print(z)

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [49]:
matrix=np.random.rand(3,3)
csum=np.cumsum(matrix)
print(csum)

[0.07624187 0.41384912 1.04118907 1.71999155 1.92346842 2.36469676
 2.85014835 2.93724531 3.92935358]
